name: ci
run-name: CI ${{ github.ref }}
on:
  push:
    branches:
      - "**"
    paths-ignore:
      - README.md
      - LICENSE.txt
      - .gitignore
      - .vscode/**
      - .devcontainer/**

jobs:
  build_python:
    name: Python | build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - uses: py-actions/flake8@v2
        with:
          # Stop the build if there are critical syntax errors
          # https://www.flake8rules.com/
          args: --select=E9,E112,E113,E703,F82,F83
      - run: |
          echo "::add-matcher::.github/flake8-error-problem-matcher.json"
          echo "::add-matcher::.github/flake8-warning-problem-matcher.json"
      - uses: py-actions/flake8@v2
        with:
          args: --exit-zero --max-line-length=120 --max-complexity=10 --per-file-ignores=__init__.py:F401
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - run: python -m pytest --cov=sag_py_fastapi_health --cov-report=xml tests
      - run: coverage-lcov
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: lcov.info
